import React from "react";
import "./App.scss";
import { ItemRow, Coupon } from "#components";
import { CouponProvider, CouponContext } from "#couponContext";
const data = [
  {
    C: "2002",
    N: "Real Madrid - Galatasaray",
    TYPE: "1",
    NID: "2146483649",
    D: "17.08.2023",
    T: "10:35",
    DAY: "Salı",
    S: "Open",
    LN: "Türkiye Süper Ligi",
    IMF: false,
    OCG: {
      1: {
        ID: "1",
        N: "Maç Sonucu",
        MBS: "4",
        SO: 1,
        OC: {
          0: {
            ID: "0",
            O: "6.71",
            N: "1",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
          1: {
            ID: "1",
            O: "4.63",
            N: "X",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
        },
      },
      2: {
        ID: "2",
        N: "Çifte Şans",
        MBS: "4",
        SO: 4,
        OC: {
          3: {
            ID: "3",
            O: "1.79",
            N: "1-X",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          4: {
            ID: "4",
            O: "2.89",
            N: "1-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          5: {
            ID: "5",
            O: "1.35",
            N: "X-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
        },
      },
      5: {
        ID: "5",
        N: "Alt/Üst 2,5 Gol",
        MBS: "4",
        SO: 2,
        OC: {
          25: {
            ID: "25",
            O: "7.34",
            N: "Alt",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
          26: {
            ID: "26",
            O: "1.51",
            N: "Üst",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
        },
      },
    },
    HEC: false,
  },
  {
    C: "2001",
    N: "PSV - AS Roma",
    TYPE: "1",
    NID: "2146483648",
    D: "12.08.2023",
    T: "01:59",
    DAY: "Perşembe",
    S: "Open",
    LN: "UEFA Şampiyonlar Ligi",
    IMF: false,
    OCG: {
      1: {
        ID: "1",
        N: "Maç Sonucu",
        MBS: "4",
        SO: 1,
        OC: {
          0: {
            ID: "0",
            O: "3.60",
            N: "1",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
          1: {
            ID: "1",
            O: "2.74",
            N: "X",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
        },
      },
      2: {
        ID: "2",
        N: "Çifte Şans",
        MBS: "4",
        SO: 4,
        OC: {
          3: {
            ID: "3",
            O: "7.79",
            N: "1-X",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          4: {
            ID: "4",
            O: "4.56",
            N: "1-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          5: {
            ID: "5",
            O: "4.78",
            N: "X-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
        },
      },
      5: {
        ID: "5",
        N: "Alt/Üst 2,5 Gol",
        MBS: "4",
        SO: 2,
        OC: {
          25: {
            ID: "25",
            O: "4.92",
            N: "Alt",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
          26: {
            ID: "26",
            O: "7.09",
            N: "Üst",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
        },
      },
    },
    HEC: false,
  },
  {
    C: "2003",
    N: "AC Milan - Osasuna",
    TYPE: "1",
    NID: "2146483650",
    D: "20.11.2023",
    T: "17:12",
    DAY: "Pazartesi",
    S: "Open",
    LN: "UEFA Avrupa Ligi",
    IMF: false,
    OCG: {
      1: {
        ID: "1",
        N: "Maç Sonucu",
        MBS: "4",
        SO: 1,
        OC: {
          0: {
            ID: "0",
            O: "6.17",
            N: "1",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
          1: {
            ID: "1",
            O: "6.51",
            N: "X",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
        },
      },
      2: {
        ID: "2",
        N: "Çifte Şans",
        MBS: "4",
        SO: 4,
        OC: {
          3: {
            ID: "3",
            O: "3.15",
            N: "1-X",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          4: {
            ID: "4",
            O: "1.64",
            N: "1-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          5: {
            ID: "5",
            O: "4.95",
            N: "X-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
        },
      },
      5: {
        ID: "5",
        N: "Alt/Üst 2,5 Gol",
        MBS: "4",
        SO: 2,
        OC: {
          25: {
            ID: "25",
            O: "7.92",
            N: "Alt",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
          26: {
            ID: "26",
            O: "2.47",
            N: "Üst",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
        },
      },
    },
    HEC: false,
  },
  {
    C: "2008",
    N: "Bayern - Beşiktaş",
    TYPE: "1",
    NID: "2146483655",
    D: "20.06.2023",
    T: "22:12",
    DAY: "Cumartesi",
    S: "Open",
    LN: "UEFA Avrupa Ligi",
    IMF: false,
    OCG: {
      1: {
        ID: "1",
        N: "Maç Sonucu",
        MBS: "4",
        SO: 1,
        OC: {
          0: {
            ID: "0",
            O: "3.53",
            N: "1",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
          1: {
            ID: "1",
            O: "2.10",
            N: "X",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
        },
      },
      2: {
        ID: "2",
        N: "Çifte Şans",
        MBS: "4",
        SO: 4,
        OC: {
          3: {
            ID: "3",
            O: "7.27",
            N: "1-X",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          4: {
            ID: "4",
            O: "3.49",
            N: "1-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          5: {
            ID: "5",
            O: "6.97",
            N: "X-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
        },
      },
      5: {
        ID: "5",
        N: "Alt/Üst 2,5 Gol",
        MBS: "4",
        SO: 2,
        OC: {
          25: {
            ID: "25",
            O: "6.33",
            N: "Alt",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
          26: {
            ID: "26",
            O: "4.07",
            N: "Üst",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
        },
      },
    },
    HEC: false,
  },
  {
    C: "2009",
    N: "Barcelona - Osasuna",
    TYPE: "1",
    NID: "2146483656",
    D: "24.03.2023",
    T: "20:16",
    DAY: "Pazartesi",
    S: "Open",
    LN: "İtalya Serie A",
    IMF: false,
    OCG: {
      1: {
        ID: "1",
        N: "Maç Sonucu",
        MBS: "4",
        SO: 1,
        OC: {
          0: {
            ID: "0",
            O: "2.54",
            N: "1",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
          1: {
            ID: "1",
            O: "5.80",
            N: "X",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
        },
      },
      2: {
        ID: "2",
        N: "Çifte Şans",
        MBS: "4",
        SO: 4,
        OC: {
          3: {
            ID: "3",
            O: "5.56",
            N: "1-X",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          4: {
            ID: "4",
            O: "4.87",
            N: "1-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          5: {
            ID: "5",
            O: "3.32",
            N: "X-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
        },
      },
      5: {
        ID: "5",
        N: "Alt/Üst 2,5 Gol",
        MBS: "4",
        SO: 2,
        OC: {
          25: {
            ID: "25",
            O: "5.62",
            N: "Alt",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
          26: {
            ID: "26",
            O: "1.28",
            N: "Üst",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
        },
      },
    },
    HEC: false,
  },
  {
    C: "2010",
    N: "PSV - Osasuna",
    TYPE: "1",
    NID: "2146483657",
    D: "30.09.2023",
    T: "04:53",
    DAY: "Salı",
    S: "Open",
    LN: "Premier League",
    IMF: false,
    OCG: {
      1: {
        ID: "1",
        N: "Maç Sonucu",
        MBS: "4",
        SO: 1,
        OC: {
          0: {
            ID: "0",
            O: "2.34",
            N: "1",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
          1: {
            ID: "1",
            O: "7.67",
            N: "X",
            MBS: "4",
            G: "1",
            OD: 0,
            IMF: false,
          },
        },
      },
      2: {
        ID: "2",
        N: "Çifte Şans",
        MBS: "4",
        SO: 4,
        OC: {
          3: {
            ID: "3",
            O: "7.57",
            N: "1-X",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          4: {
            ID: "4",
            O: "4.01",
            N: "1-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
          5: {
            ID: "5",
            O: "2.43",
            N: "X-2",
            MBS: "4",
            G: "2",
            OD: 0,
            IMF: false,
          },
        },
      },
      5: {
        ID: "5",
        N: "Alt/Üst 2,5 Gol",
        MBS: "4",
        SO: 2,
        OC: {
          25: {
            ID: "25",
            O: "7.61",
            N: "Alt",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
          26: {
            ID: "26",
            O: "6.05",
            N: "Üst",
            MBS: "4",
            G: "5",
            OD: 0,
            IMF: false,
          },
        },
      },
    },
    HEC: false,
  },
];

const App = () => {
  return (
    <CouponProvider>
      <Coupon />
      <div>
        <table>
          <tbody>
            {data.map((item, index) => {
              return <ItemRow item={item} key={index}></ItemRow>;
            })}
          </tbody>
        </table>
      </div>
    </CouponProvider>
  );
};

export default App;
